apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: turbine-consumer-scaler
spec:
  scaleTargetRef:
    name: turbine-consumer
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        consumerGroup: turbine-cms-consumer-k8s
        topic: features
        lagThreshold: "10"
