apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbine-consumer
  template:
    metadata:
      labels:
        app: turbine-consumer
    spec:
      containers:
        - name: consumer
          image: turbine-consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
