apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: timescaledb
  DB_NAME: CHANGE_ME
  DB_USER: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
  GF_SECURITY_ADMIN_PASSWORD: CHANGE_ME
